gazebo_ros_control:
  pid_gains:
    sero_1_j1: {p: 100, i: 1, d: 1, i_clamp: 1}
    sero_1_j2: {p: 100, i: 1, d: 1, i_clamp: 1}
    sero_1_j3: {p: 100, i: 1, d: 1, i_clamp: 1}
    sero_1_j4: {p: 100, i: 1, d: 1, i_clamp: 1}
    sero_1_j5: {p: 100, i: 1, d: 1, i_clamp: 1}
    sero_1_j6: {p: 100, i: 1, d: 1, i_clamp: 1}
    sero_2_j1: {p: 100, i: 1, d: 1, i_clamp: 1}
    sero_2_j2: {p: 100, i: 1, d: 1, i_clamp: 1}
    sero_2_j3: {p: 100, i: 1, d: 1, i_clamp: 1}
    sero_2_j4: {p: 100, i: 1, d: 1, i_clamp: 1}
    sero_2_j5: {p: 100, i: 1, d: 1, i_clamp: 1}
    sero_3_j1: {p: 100, i: 1, d: 1, i_clamp: 1}
    sero_3_j2: {p: 100, i: 1, d: 1, i_clamp: 1}
    sero_3_j3: {p: 100, i: 1, d: 1, i_clamp: 1}
    sero_3_j4: {p: 100, i: 1, d: 1, i_clamp: 1}
    sero_3_j5: {p: 100, i: 1, d: 1, i_clamp: 1}