controller_list:
  - name: fake_sero_1_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - sero_1_j1
      - sero_1_j2
      - sero_1_j3
      - sero_1_j4
      - sero_1_j5
      - sero_1_j6
  - name: fake_sero_2_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - sero_2_j1
      - sero_2_j2
      - sero_2_j3
      - sero_2_j4
      - sero_2_j5
      - sero_2_j6
  - name: fake_sero_3_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - sero_3_j1
      - sero_3_j2
      - sero_3_j3
      - sero_3_j4
      - sero_3_j5
initial:  # Define initial robot poses per group
  - group: sero_1_arm
    pose: sero_1_home
  - group: sero_2_arm
    pose: sero_2_home
  - group: sero_3_arm
    pose: sero_3_home