<<<<<<< HEAD
# @file simple_moveit_controllers.yaml
# @package sero_multi_station_moveit_config
# @brief Defines MoveIt controller handles for each robot arm.
#
# This file is used by the simple MoveIt controller manager plugin.
# It maps each controller name to a trajectory action interface and joint list.

=======
>>>>>>> d5173fffd94fab46ff3292e3aa4704e5f5ab3f23
controller_list:
  - name: sero_1_ctrl
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - sero_1_j1
      - sero_1_j2
      - sero_1_j3
      - sero_1_j4
      - sero_1_j5
<<<<<<< HEAD
      - sero_1_j6
=======
>>>>>>> d5173fffd94fab46ff3292e3aa4704e5f5ab3f23
  - name: sero_2_ctrl
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - sero_2_j1
      - sero_2_j2
      - sero_2_j3
      - sero_2_j4
      - sero_2_j5
<<<<<<< HEAD
      - sero_2_j6
=======
>>>>>>> d5173fffd94fab46ff3292e3aa4704e5f5ab3f23
  - name: sero_3_ctrl
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - sero_3_j1
      - sero_3_j2
      - sero_3_j3
      - sero_3_j4
      - sero_3_j5