sero1_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - j1
    - j2
    - j3
    - j4
    - j5
  gains:
    j1:
      p: 20000
      d: 1000
      i: 100
      i_clamp: 100
    j2:
      p: 20000
      d: 1000
      i: 100
      i_clamp: 10
    j3:
      p: 20000
      d: 100
      i: 1
      i_clamp: 1
    j4:
      p: 20000
      d: 10
      i: 1
      i_clamp: 1
    j5:
      p: 1000
      d: 10
      i: 1
      i_clamp: 1
sero1_ee_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - jendeffector
  gains:
    jendeffector:
      p: 1000
      d: 10
      i: 1
      i_clamp: 1


sero2_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - j1
    - j2
    - j3
    - j4
    - j5
  gains:
    j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1