controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
  - name: fake_ee_controller
    type: $(arg fake_execution_type)
    joints:
      - jendeffector
initial:  # Define initial robot poses per group
  - group: arm
    pose: home_pose