# Publish joint_states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - j1
    - j2
    - j3
    - j4
    - j5
  gains:
    j1: {p: 20000, d: 1000, i: 100, i_clamp: 100}
    j2: {p: 20000, d: 1000, i: 100, i_clamp: 10}
    j3: {p: 20000, d: 100, i: 1, i_clamp: 1}
    j4: {p: 20000, d: 10, i: 1, i_clamp: 1}
    j5: {p: 1000, d: 10, i: 1, i_clamp: 1}

ee_controller:
  type: position_controllers/JointTrajectoryController
  joints: [jendeffector]
  gains:
    jendeffector: {p: 1000, d: 10, i: 1, i_clamp: 1}