joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - j1
    - j2
    - j3
    - j4
    - j5

ee_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - jendeffector
